monero_path="/home/user/monero-gui-v0.18.2.2/extras"
monero_rpc="$monero_path/monero-wallet-rpc"
params="--testnet --untrusted-daemon --log-file /dev/null"
bind_port="28088"
wallet_file="$monero_path/MFrelance"
wallet_password="123"
rpcLogin="monero:rpcPassword"
moneroNode="http://testnet.xmr-tw.org:28081"
$monero_rpc --rpc-bind-port $bind_port --wallet-file "$wallet_file" --daemon-address "$moneroNode" $params --password "$wallet_password" --rpc-login "$rpcLogin"
